
#include "Motor.h"



void MOTOR_A_INIT(void){
	DIO_Init(MOTOR_PORT,MOTOR_A_ENABLE,IN,PULLDOWN);
	DIO_Init(MOTOR_PORT, MOTOR_A_PIN0,OUT,PULLDOWN);
	DIO_Init(MOTOR_PORT,MOTOR_A_PIN1,OUT,PULLDOWN);
}


void MOTOR_B_INIT(void){
	DIO_Init(MOTOR_PORT,MOTOR_B_ENABLE,IN,PULLDOWN);
	DIO_Init(MOTOR_PORT, MOTOR_B_PIN0,OUT,PULLDOWN);
	DIO_Init(MOTOR_PORT, MOTOR_B_PIN1,OUT,PULLDOWN);
}


void MOTOR_A_FORWARD(void){
	DIO_WritePin(MOTOR_PORT,MOTOR_A_PIN0,LOW);
	DIO_WritePin(MOTOR_PORT,MOTOR_A_PIN1,HIGH);
}


void MOTOR_A_BACKWARD(void){
	DIO_WritePin(MOTOR_PORT,MOTOR_A_PIN0,HIGH);
	DIO_WritePin(MOTOR_PORT,MOTOR_A_PIN1,LOW);
}

void MOTOR_B_FORWARD(void){
	DIO_WritePin(MOTOR_PORT,MOTOR_B_PIN0,LOW);
	DIO_WritePin(MOTOR_PORT,MOTOR_B_PIN1,HIGH);
}

void MOTOR_B_BACKWARD(void){
	DIO_WritePin(MOTOR_PORT,MOTOR_B_PIN0,HIGH);
	DIO_WritePin(MOTOR_PORT,MOTOR_B_PIN1,LOW);
}

void MOTOR_A_STOP()
{
	DIO_WritePin(MOTOR_PORT,MOTOR_A_PIN0,LOW);
	DIO_WritePin(MOTOR_PORT,MOTOR_A_PIN1,LOW);
}


void MOTOR_B_STOP()
{
	DIO_WritePin(MOTOR_PORT,MOTOR_B_PIN0,LOW);
	DIO_WritePin(MOTOR_PORT,MOTOR_B_PIN1,LOW);
}
